# visual_config.yaml
input_directory: "../spectra/MTBLS/"
output_directory: "../output/images/"
log_directory: "../logs/"
video_output_path: "../output/images/"
file_types:
  - "*.mzML"
n_workers: 4

ms_parameters:
  ms1_threshold: 1000.0
  ms2_threshold: 100.0
  mz_tolerance: 0.01
  rt_tolerance: 0.5
  min_intensity: 100.0
  output_dir: "processed_output"
