ms_parameters:
  ms1_threshold: 1000
  ms2_threshold: 100
  mz_tolerance: 0.01
  rt_tolerance: 0.5
  min_intensity: 500
  output_dir: "output"
  n_workers: -1  # Use all available CPUs

compute_parameters:
  chunk_size_mb: 1024  # Size of each processing chunk in MB
  memory_fraction: 0.8  # Fraction of system memory to use
  use_gpu: false       # Enable GPU acceleration if available

storage:
  format: "zarr"       # Use zarr for efficient storage
  compression: "lz4"   # Fast compression algorithm
  chunk_size: 1000000  # Number of rows per chunk

logging:
  level: INFO
  format: '%(asctime)s - %(levelname)s - %(message)s'
  file: 'ms_processing.log'
