theme: jekyll-theme-cayman
title: Lavoisier
description: High-performance computing solution for mass spectrometry-based metabolomics data analysis
show_downloads: true
google_analytics:
plugins:
  - jekyll-relative-links
  - jekyll-seo-tag
relative_links:
  enabled: true
  collections: true 