# GitHub Pages configuration
remote_theme: just-the-docs/just-the-docs

title: Lavoisier
description: High-performance computing solution for mass spectrometry-based metabolomics data analysis
url: https://fullscreen-triangle.github.io
baseurl: /lavoisier

# Theme configuration
color_scheme: light
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true

# Navigation
nav_external_links:
  - title: GitHub Repository
    url: https://github.com/fullscreen-triangle/lavoisier

# Footer
footer_content: "Copyright &copy; 2024 Lavoisier Project. Distributed under the MIT License."

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-relative-links

# GitHub Pages settings
github:
  repository_url: "https://github.com/fullscreen-triangle/lavoisier"

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
  syntax_highlighter: rouge

# Math support with MathJax
mathjax:
  enable: true
  combo: "tex-mml-chtml"
  tex:
    inlineMath: [['$', '$'], ['\\(', '\\)']]
    displayMath: [['$$', '$$'], ['\\[', '\\]']]
    processEscapes: true
    processEnvironments: true
    tags: 'ams'
  options:
    ignoreHtmlClass: "tex2jax_ignore"
    processHtmlClass: "tex2jax_process"

# Enable math processing in markdown
math_engine: mathjax

# Additional head content for MathJax
head_custom: |
  <script>
  MathJax = {
    tex: {
      inlineMath: [['$', '$'], ['\\(', '\\)']],
      displayMath: [['$$', '$$'], ['\\[', '\\]']],
      processEscapes: true,
      processEnvironments: true,
      tags: 'ams'
    },
    options: {
      ignoreHtmlClass: 'tex2jax_ignore',
      processHtmlClass: 'tex2jax_process'
    }
  };
  </script>
  <script type="text/javascript" id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script> 