# GitHub Pages configuration
remote_theme: just-the-docs/just-the-docs

title: Lavoisier
description: High-performance computing solution for mass spectrometry-based metabolomics data analysis
url: https://fullscreen-triangle.github.io
baseurl: /lavoisier

# Theme configuration
color_scheme: light
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true

# Navigation
nav_external_links:
  - title: GitHub Repository
    url: https://github.com/fullscreen-triangle/lavoisier

# Footer
footer_content: "Copyright &copy; 2024 Lavoisier Project. Distributed under the MIT License."

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-relative-links

# GitHub Pages settings
github:
  repository_url: "https://github.com/fullscreen-triangle/lavoisier"

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax

# Math support
mathjax:
  source: https://polyfill.io/v3/polyfill.min.js?features=es6
  config: MathJax.tex2jax.inlineMath=[['$','$'],['\\(','\\)']];MathJax.tex2jax.displayMath=[['$$','$$'],['\\[','\\]']]; 